// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $index from "./routes/index.tsx";
import * as $webauthn_reg_options from "./routes/webauthn/reg/options.ts";
import * as $webauthn_reg_verify from "./routes/webauthn/reg/verify.ts";
import * as $webauthn_reg_islands_RegButton from "./routes/webauthn/reg/(_islands)/RegButton.tsx";
import * as $webauthn_reg_islands_RegDialog from "./routes/webauthn/reg/(_islands)/RegDialog.tsx";
import * as $webauthn_reg_islands_RegForm from "./routes/webauthn/reg/(_islands)/RegForm.tsx";
import * as $webauthn_reg_islands_RegProgressDialog from "./routes/webauthn/reg/(_islands)/RegProgressDialog.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/index.tsx": $index,
    "./routes/webauthn/reg/options.ts": $webauthn_reg_options,
    "./routes/webauthn/reg/verify.ts": $webauthn_reg_verify,
  },
  islands: {
    "./routes/webauthn/reg/(_islands)/RegButton.tsx":
      $webauthn_reg_islands_RegButton,
    "./routes/webauthn/reg/(_islands)/RegDialog.tsx":
      $webauthn_reg_islands_RegDialog,
    "./routes/webauthn/reg/(_islands)/RegForm.tsx":
      $webauthn_reg_islands_RegForm,
    "./routes/webauthn/reg/(_islands)/RegProgressDialog.tsx":
      $webauthn_reg_islands_RegProgressDialog,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
